version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - gocritic
    - nolintlint

linters-settings:
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - hugeParam
  misspell:
    locale: US

output:
  formats:
    colored-line-number: {}

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
